{% set version = "0.11.1" %}

package:
  name: terminado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/terminado/terminado-{{ version }}.tar.gz
  sha256: 962b402edbb480718054dc37027bada293972ecadfb587b89f01e2b8660a2132

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - flit
    - pip
    - python
  run:
    - ptyprocess  # [not win]
    - python
    - pywinpty >=1.1  # [win]
    - tornado >=4

test:
  requires:
    - pip
    - posix  # [win]
    - pytest
    - pytest-cov
  imports:
    - terminado
  commands:
    # see run_test.py for more
    - python -m pip check

about:
  home: https://github.com/jupyter/terminado
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Terminals served by tornado websockets
  description: |
    This is a Tornado websocket backend for the Xterm.js Javascript terminal emulator library.
  doc_url: http://terminado.readthedocs.org/en/latest/
  doc_source_url: https://github.com/jupyter/terminado/blob/master/doc/index.rst
  dev_url: https://github.com/jupyter/terminado

extra:
  recipe-maintainers:
    - blink1073
    - pelson
    - takluyver
    - ocefpaf
    - bollwyvl
